### ISSUE TITLE
'System.NotImplementedException' in Anotar.Serilog.dll

### ISSUE THREAD

**Issue by NPSF3000** [Fody/Anotar#131] opened 2018-05-11 18:33 UTC
Trying to upgrade to Fody 3.0.* to resolve https://github.com/Fody/Fody/issues/499 but get the following:

```
Exception thrown: 'System.NotImplementedException' in Anotar.Serilog.dll
: 'System.NotImplementedException' in Anotar.Serilog.dll
Exception thrown: 'System.NotImplementedException' in Anotar.Serilog.dll
An exception of type 'System.NotImplementedException' occurred in Anotar.Serilog.dll but was not handled in user code
The method or operation is not implemented.
```

When calling `Log.Error(...);`

Packages:

```
  <package id="Anotar.Serilog.Fody" version="4.3.2" targetFramework="net452" developmentDependency="true" />
  <package id="Fody" version="3.0.3" targetFramework="net452" developmentDependency="true" />
  <package id="FodyPackaging" version="3.0.3" targetFramework="net452" />
  <package id="Serilog" version="2.6.0" targetFramework="net452" />
  <package id="Serilog.Enrichers.Process" version="2.0.1" targetFramework="net452" />
  <package id="Serilog.Enrichers.Thread" version="3.0.0" targetFramework="net452" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net452" />
  <package id="Serilog.Sinks.ColoredConsole" version="3.0.1" targetFramework="net452" />
  <package id="Serilog.Sinks.Console" version="3.0.1" targetFramework="net452" />
  <package id="Serilog.Sinks.File" version="3.2.0" targetFramework="net452" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.1.1" targetFramework="net452" />
  <package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net452" />
  <package id="Serilog.Sinks.Seq" version="3.3.3" targetFramework="net452" />

```

**Comment by SimonCropp** [comment] 2018-05-12 00:31
have u added the xml entry https://github.com/Fody/Anotar#add-to-fodyweaversxml  ?

**Comment by SimonCropp** [comment] 2018-05-12 02:29
duplicate of https://github.com/Fody/Anotar/issues/130

**Closed by SimonCropp** 2018-05-12 02:29 UTC
